HOUSE_CLEANING = [
    "Standard Cleaning",
    "Deep Cleaning",
    "Move-in/Move-out Cleaning",
    "Window Washing (Interior)",
    "Appliance Cleaning (Interior)",
    "Bi-weekly Service",
    "Monthly Service",
    "Laundry Service (Fold Only)",
    "Eco-Friendly Cleaning",
    "Post-Renovation Cleaning",
    "Office Cleaning",
    "Carpet Spot Cleaning",
    "Kitchen De-greasing",
    "Bathroom Sanitization",
    "Dusting & Vacuuming",
    "One-Time Cleaning",
    "Event Clean-up",
    "Pantry Organization",
    "Closet Organization",
    "Luxury Home Cleaning",
    "Vacation Rental Turnover",
    "Green Cleaning Products Only",
    "Personalized Cleaning Plans",
    "Blind & Drape Cleaning",
    "Baseboard Cleaning",
    "Wall Spot Cleaning",
    "Express Clean (2-hour limit)",
    "Post-Construction Cleaning (Light)",
    "Garage Sweeping",
]
LAWN_AND_GARDEN = [
    "Lawn Mowing",
    "Edging",
    "Weeding",
    "Fertilization",
    "Aeration",
    "Pest Control (Lawn)",
    "Hedge Trimming",
    "Leaf Removal",
    "Seasonal Clean-up",
    "Garden Maintenance",
    "Planting & Design",
    "Shrub Care",
    "Mulching",
    "Small Tree Pruning",
    "Tree Trimming",
    "Stump Removal",
    "Tree Removal",
    "Emergency Storm Clean-up",
    "Weed Control (Lawn)",
    "Pressure Washing (Patios/Walkways)",
    "Gutter Cleaning",
    "Landscape Design",
    "Hardscaping (Patios, Walkways)",
    "Irrigation System Installation & Repair",
    "Water Features",
    "Lawn Mowing (Weekly/Bi-Weekly)",
    "Blowing",
    "Bush Trimming",
    "Artistic Pruning",
    "Orchard Care",
    "Hedge Sculpting",
    "Disease & Pest Inspection (Trees/Shrubs)",
]

HANDYMAN_AND_REPAIRS = [
    "Minor Plumbing Repairs",
    "Electrical Fixture Installation",
    "Drywall Patching",
    "Door & Window Repair",
    "Furniture Assembly",
    "Picture Hanging",
    "General Home Maintenance",
    "Deck Repair & Staining",
    "Fence Installation & Repair",
    "Gutter Cleaning & Repair",
    "TV Mounting",
    "Appliance Installation (Non-Gas)",
    "Cabinet Repair",
    "Tile & Grout Repair",
    "Painting (Small Jobs)",
    "Light Carpentry",
    "Smart Home Device Setup",
    "Child-Proofing Installation",
    "Pet Door Installation",
    "Accessibility Modifications (Ramps, Grab Bars)",
    "Pressure Washing (Exterior)",
    "Leaky Faucet Repair",
    "Running Toilet Repair",
    "Light Bulb Replacement (High Ceilings)",
    "Smoke Detector Battery Replacement",
    "Minor Landscaping Cleanup",
    "Custom Shelving",
    "Crown Molding Installation",
    "Detailed Woodwork Repair",
    "Small Remodeling Projects (Bath/Kitchen)",
    "Flooring Repair (Hardwood/Laminate)",
    "Ceiling Fan Installation",
    "Door Knob & Lock Replacement",
    "Wall Art & Mirror Hanging (Heavy Items)",
    "Blind & Curtain Rod Installation",
    "Baby Gate Installation",
    "General Handyman Services",
    "Emergency Minor Repairs (Burst Pipe, etc.)",
    "Vent Cleaning (Dryer, Bathroom)",
    "Weather Stripping Installation",
    "Screen Repair (Doors/Windows)",
]
EXTERIOR_CLEANING = (
    [
        "House Pressure Washing (Siding, Brick)",
        "Driveway & Sidewalk Pressure Washing",
        "Deck & Patio Cleaning",
        "Fence Pressure Washing",
        "Soft Washing (Delicate Surfaces)",
        "Gutter Cleaning (Debris Removal)",
        "Gutter Brightening (Exterior)",
        "Downspout Flushing",
        "Minor Gutter Repair",
        "Roof Moss Removal (Gentle)",
        "Exterior Window Cleaning (Residential)",
        "Screen Cleaning",
        "Window Sill Wiping",
        "Solar Panel Cleaning",
        "Skylight Cleaning",
        "Concrete Sealing (Post-Wash)",
        "Paver Cleaning & Sealing",
        "Rust Stain Removal (Exterior)",
        "Oil Stain Removal (Driveway)",
        "Roof Soft Washing (Algae/Moss)",
        "Siding Soft Washing (Vinyl, Stucco)",
        "Soffit & Fascia Cleaning",
        "Exterior Building Washing (Commercial)",
        "Drive-thru Cleaning (Commercial)",
        "Dumpster Pad Cleaning",
        "Parking Lot Stripping (Light Cleaning)",
        "Graffiti Removal (Non-Porous Surfaces)",
        "Deck Cleaning & Restoration",
        "Patio Furniture Cleaning",
        "Awning Cleaning",
        "Outdoor Kitchen Cleaning (Exterior)",
        "Post-Construction Exterior Clean-up",
        "New Home Exterior Wash",
        "Vacation Rental Exterior Detailing",
        "Seasonal Exterior Maintenance Packages",
    ],
)
SPECIALIZED_CLEANING = [
    "Crime Scene Clean-up",
    "Unattended Death Clean-up",
    "Hoarding Clean-up & Remediation",
    "Bloodborne Pathogen Remediation",
    "Odor Removal (Severe Cases)",
    "HVAC Duct Cleaning (Residential)",
    "Dryer Vent Cleaning (Deep)",
    "Furnace & AC Coil Cleaning",
    "Air Quality Testing",
    "Mold Remediation (Ducts)",
    "Water Extraction & Drying",
    "Flood Damage Restoration",
    "Fire & Smoke Damage Clean-up",
    "Soot & Ash Removal",
    "Contents Cleaning & Restoration",
    "Structural Drying",
    "Mold Inspection & Testing",
    "Mold Removal & Remediation",
    "Black Mold Treatment",
    "Preventative Mold Solutions",
    "Crawl Space Encapsulation (Mold Prevention)",
    "Steam Carpet Cleaning",
    "Stain & Spot Removal (Carpet/Upholstery)",
    "Pet Odor & Stain Removal",
    "Area Rug Cleaning (On-site/Off-site)",
    "Commercial Carpet Cleaning",
    "Graffiti Removal (All Surfaces)",
    "Biohazard Waste Disposal (Non-Medical)",
    "Debris Removal (Storm/Vandalism)",
    "Board-Up Services (Emergency)",
    "Tile & Grout Deep Cleaning",
    "Grout Sealing & Color Sealing",
    "Tile Polishing & Honing",
    "Stone Floor Cleaning & Restoration",
    "Hard Surface Cleaning",
    "Commercial Kitchen Hood & Exhaust Cleaning",
    "Grease Trap Cleaning",
    "Floor & Wall Degreasing",
    "Equipment Deep Cleaning",
    "Sanitization & Disinfection (Commercial Kitchens)",
]
ASSEMBLY_AND_INSTALLATION = [
    "Furniture Assembly (IKEA, Wayfair, etc.)",
    "Grill Assembly",
    "Fitness Equipment Assembly (Treadmills, Bikes)",
    "Playset & Trampoline Assembly",
    "Shed Assembly (Prefab)",
    "TV Mounting (Wall, Ceiling)",
    "Sound System Installation (Home Theater)",
    "Smart Home Device Setup & Integration",
    "Security Camera Installation (Wireless)",
    "Wi-Fi Extender Setup",
    "Lighting Fixture Installation",
    "Ceiling Fan Installation",
    "Cabinet & Shelf Installation",
    "Blind & Curtain Rod Installation",
    "Picture & Mirror Hanging (Heavy)",
    "Dishwasher Installation (Pre-plumbed)",
    "Washing Machine & Dryer Hook-up",
    "Range Hood Installation",
    "Garbage Disposal Replacement",
    "Oven/Stove Installation (Electric)",
    "Patio Furniture Assembly",
    "Gazebo & Pergola Assembly (Kit)",
    "Outdoor Lighting Installation",
    "Garden Shed Installation (Small)",
    "Hose Reel Installation",
    "Office Furniture Assembly",
    "Cubicle Installation",
    "Retail Display Assembly",
    "Gym Equipment Setup (Commercial)",
    "Warehouse Shelving Installation",
    "Custom Closet System Installation",
    "Built-in Shelving & Cabinetry (Kit)",
    "Wall Bed Installation",
    "Pet Door Installation (Complex)",
    "Floating Shelf Installation",
    "Interior Door Installation",
    "Exterior Door Replacement",
    "Smart Lock Installation",
    "Deadbolt Installation",
    "Sliding Door Repair/Installation",
]
